# Generated by Django 4.1.7 on 2023-03-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="record",
            name="email",
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name="record",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
